# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f905810635e413de3b87850db08527207a7205b77db01e394a7bd706e097d89ac3f843eac6d197df3d1a86d3a627fe77db7b61ba44871bfba93057ec6dae3ba7

test:
  secret_key_base: afb15b22d057140bce4c581416a2a67f5a06eff62a500a0318d5554641f59b9afcec076a816545cf842de0d9c627300baefec2e8e0d2fdc9de55c22fb774e428

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
